name: Exampleplugin
version: '${version}'
main: de.otto.minecrafttutorium.exampleplugin.Exampleplugin
api-version: 1.19
authors: [ Mika, Janik ]
description: Example Plugin for Minecraft Paper 1.19.2

commands:
  scare:
    description: Scares you
    usage: /scare <number between 1 and 3>
  firesword:
    description: Gives you a firesword
    usage: /firesword
  chatcolor:
    description: Changes your chatcolor
    usage: /chatcolor [<HEX>] [<R>, <G>, <B>]
  nickname:
    description: Changes your nickname
    usage: /nickname <nickname>
  tpworld:
    description: Teleport in a world
    usage: /tpworld <world> <x> <y> <z>